name: bitcoindart
description: A dart Bitcoin library for Flutter. BIP32, BIP39, P2PKH integration.
version: 2.2.1
homepage: https://github.com/keybagio/bitcoindart
author: KY <harrykyguo@gmail.com>

environment:
  sdk: ">=2.12.0 <3.0.0"
publish_to: none
dependencies:
  bech32:
    git:
      url: https://github.com/frankie060392/bech32.git
      ref: master
  bip39: ^1.0.6
  bip32: ^2.0.0
  # bip32: ^1.0.7
  # bip39: ^1.0.3
  pointycastle: ^3.4.0
  # pointycastle: ^1.0.2
  # hex: ^0.1.2
  hex: ^0.2.0
  bs58check: ^1.0.1
  meta: ^1.2.4
  
dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.9.0
